services:
  cm-grasshopper:
    container_name: cm-grasshopper
    restart: always
    image: cloudbaristaorg/cm-grasshopper:edge
    volumes:
      #- ./softwares.db:/root/.cm-grasshopper/softwares.db:rw
      #- ./CM-GRASSHOPPER.db:/root/.cm-grasshopper/CM-GRASSHOPPER.db:rw
      #- ./honeybee.key:/root/.cm-grasshopper/honeybee.key:ro
      #- ./playbook:/playbook/:rw
      - ./software_temp:/software_temp:rw
      - ./software_log:/software_log:rw
    network_mode: "host"
