services:
  cm-grasshopper:
    container_name: cm-grasshopper
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: cm-grasshopper:${TAG:-latest}
    volumes:
      - ./CM-GRASSHOPPER.db:/CM-GRASSHOPPER.db:rw
      - ./contents-home:/contents-home/:rw
    network_mode: "host"
