services:
  cm-grasshopper:
    container_name: cm-grasshopper
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    image: cloudbaristaorg/cm-grasshopper:edge
    volumes:
      #- ./CM-GRASSHOPPER.db:/CM-GRASSHOPPER.db:rw
      #- ./honeybee.key:/root/.cm-grasshopper/honeybee.key:ro
      - ./software_temp:/software_temp:rw
      - ./software_log:/software_log:rw
      - ./playbook:/playbook/:rw
    network_mode: "host"
