### Source install
POST {{baseUrl}}/velero/source/install
Content-Type: application/json

{
  "sourceCluster": {
    "name": "source-cluster",
    "namespace": "velero",
    "kubeconfig": "{{base64_source_kubeconfig}}"
  },
  "storage": {
    "s3": {
      "endpoint": "{{s3_endpoint}}",
      "accessKey": "{{s3_accesskey}}",
      "secretKey": "{{s3_secretkey}}",
      "bucket": "{{s3_bucket}}",
      "useSSL": false
    }
  },
  "install": {
    "force": false,
    "volumeBackupMode": "filesystem"
  }
}

### Target install
POST {{baseUrl}}/velero/target/install
Content-Type: application/json

{
  "targetCluster": {
    "name": "target-cluster",
    "namespace": "velero",
    "kubeconfig": "{{base64_target_kubeconfig}}"
  },
  "storage": {
    "s3": {
      "endpoint": "{{s3_endpoint}}",
      "accessKey": "{{s3_accesskey}}",
      "secretKey": "{{s3_secretkey}}",
      "bucket": "{{s3_bucket}}",
      "useSSL": false
    }
  },
  "install": {
    "force": false,
    "volumeBackupMode": "filesystem"
  }
}
